col_discard = [
'ARM Balloon Indicator', 'ARM Cap Structure', 'ARM Initial Fixed-Rate Period  ? 5 YR Indicator',
'ARM Plan Number', 'ARM Product Type', 'Alternative Delinquency Resolution', 'Alternative Delinquency Resolution Count',
'Asset Recovery Costs', 'Associated Taxes for Holding Property', 'Borrower Credit Score At Issuance',
'Borrower Credit Score Current', 'Channel', 'Co-Borrower Credit Score At Issuance', 'Co-Borrower Credit Score Current',
'Credit Enhancement Proceeds', 'Cumulative Credit Event Net Gain or Loss', 'CumulativeModification Loss Amount',
'Current List Price', 'Current List Start Date', 'Current Period Credit Event Net Gain or Loss',
'Current Period Modification Loss Amount', 'Deal Name', 'Disposition Date', 'First Payment Date', 'Foreclosure Costs', 'Foreclosure Principal Write-off Amount', 'High Loan to Value (HLTV) Refinance Option Indicator',
'Index', 'Initial Fixed-Rate Period', 'Initial Interest Rate Cap Up Percent',
'Interest Only First Principal And Interest Payment Date', 'Interest Only Loan Indicator', 'Interest Rate Adjustment Frequency',
'Last Paid Installment Date', 'Lifetime Interest Rate Cap Up Percent', 'Loan Holdback Effective Date', 'Loan Holdback Indicator',
'Loan Purpose', 'Master Servicer', 'Metropolitan Statistical Area (MSA)', 'Miscellaneous Holding Expenses and Credits',
'Months to Amortization', 'Mortgage Insurance Cancellation Indicator', 'Mortgage Insurance Type',
'Mortgage Margin', 'Net Sales Proceeds', 'Next Interest Rate Adjustment Date', 'Next Payment Change Date',
'Non-Interest Bearing UPB', 'Number of Units', 'Occupancy Status', 'Original Combined Loan to Value Ratio (CLTV)',
'Original List Price', 'Original List Start Date', 'Other Foreclosure Proceeds', 'Periodic Interest Rate Cap Up Percent',
'Prepayment Penalty Indicator', 'Principal Forgiveness Amount', 'Property Preservation and Repair Costs',
'Property State', 'Property Type', 'Reference Pool ID', 'Relocation Mortgage Indicator', 'Remaining Months To Maturity',
'Remaining Months to Legal Maturity', 'Repurchase Date', 'Repurchase Make Whole Proceeds', 'Repurchase Make Whole Proceeds Flag',
'Scheduled Principal Current', 'Seller Name', 'Servicer Name', 'Servicing Activity Indicator', 'Total Deferral Amount',
'Total Principal Current', 'UP Bat Issuance', 'UPB at the Time of Removal', 'Unscheduled Principal Current',
'Zero Balance Code', 'Zero Balance Code Change Date', 'Zero Balance Effective Date', 'Zip Code Short', 'Mortgage Insurance Percentage',
'Delinquent Accrued Interest', 'Loan Payment History', 'Property Valuation Method',  'Current Actual UPB'
]